import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'no_account_found_for_email': 'No account found for that email.',
      'password_reset_success': 'Password reset successfully!',
      'verify_email': 'Verify email',
      'email_found_enter_new_password': 'Email found. Please enter your new password.',
      'reset_password': 'Reset password',
      'password_too_short': 'Password must be at least 6 characters',
  'name_label': 'Full name',
      'enter_name': 'Please enter your name',
      'enter_phone': 'Please enter your phone number',
      'enter_valid_email': 'Please enter a valid email',
      'email_already_used': 'This email is already in use.',
      'register_success': 'Registration successful! You can now login.',
      'register': 'Register',
      'register_with_google': 'Register with Google',
      'new_password_empty': 'New password cannot be empty',
      'passwords_do_not_match': 'Passwords do not match',
      'current_password_incorrect': 'Current password incorrect',
      'password_changed': 'Password updated',
      'delete_account': 'Delete account',
      'delete_account_confirm': 'Are you sure you want to delete your account? This action is irreversible.',
      'account_deleted': 'Account deleted',
      'email_label': 'Email',
      'password_label': 'Password',
      'forgot_password': 'Forgot password?',
      'login': 'Login',
      'login_with_google': 'Sign in with Google',
      'no_account_register': 'No account? Register',
      'banned_account': 'This account has been banned.',
      'incorrect_credentials': 'Email or password incorrect.',
      'google_cancelled': 'Google sign-in cancelled',
      'enter_email': 'Please enter your email',
      'enter_password': 'Please enter your password',
      'app_title': 'Il Gabbiano',
      'our_menu': 'Our Menu',
      'menu_empty': 'Menu is empty for now.',
      'added_to_cart': '{item} added to cart',
      'cart': 'Cart',
      'place_order': 'Place Order',
      'empty_cart': 'Your cart is empty.',
      'confirm_delete': 'Confirm deletion',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'save': 'Save',
      'pick_image_error': 'Error picking image',
      'image_saved': 'Image saved',
      'error': 'Error: {msg}',
      'no_feedbacks': 'No feedback yet.',
      'feedback_deleted': 'Feedback deleted.',
      'reservation_sent': 'Reservation sent successfully!',
      'reservation_updated': 'Reservation updated successfully!',
      'order_success': 'Order placed successfully!',
      'photo_saved': 'Photo saved',
      'profile_updated': 'Profile updated successfully!',
  'address_label': 'Address',
  'current_password_label': 'Current password',
  'new_password_label': 'New password',
  'confirm_password_label': 'Confirm password',
  'location_services_disabled': 'Services de localisation désactivés',
  'permission_denied_forever_title': 'Permission de localisation requise',
  'permission_denied_forever_message': 'Veuillez activer la permission de localisation dans les paramètres de l\'application pour utiliser cette fonctionnalité.',
  'open_settings': 'Ouvrir les paramètres',
  'get_position_failed': 'Impossible d\'obtenir la position actuelle',
  
  'reservation_details': 'Reservation Details',
  'choose_date': 'Choose a date',
  'choose_time': 'Choose a time',
  'select_date_time': 'Please select date and time',
  'number_of_people': 'Number of people',
  'required_field': 'Required field',
  'notes_optional': 'Notes (optional)',
  'modify': 'Modify',
  'reserve_action': 'Reserve',
      'menu': 'Order',
      'reserve': 'Reserve',
      'my_orders': 'My Orders',
    'my_reservations': 'My Reservations',
    'support': 'Support',
  'add_to_cart': 'Add',
  'add_to_cart_failed': 'Could not add to cart',
      'feedback': 'Feedback',
      'complaints': 'Complaints',
      'restaurant_info': 'Restaurant Info',
      'logout': 'Logout',
      'profile': 'Profile',
      'language': 'Language',
      'yes': 'Yes',
      'no': 'No',
      'send': 'Send',
      'update': 'Update',
      'user_not_identified': 'Error: user not identified.',
      'select_rating': 'Please select a star rating.',
      'thank_you_feedback': 'Thank you for your feedback!',
      'delete_feedback': 'Delete feedback',
      'delete_feedback_confirm': 'Are you sure you want to delete your feedback?',
      'comment_optional': 'Comment (optional)',
      'comment_hint': 'Leave us your impressions...',
      'rating_prompt': 'What rating would you give us?',
      'complaint_history': 'Complaint History',
      'no_complaints': 'No complaints found.',
      'complaint_deleted': 'Complaint deleted successfully.',
      'delete_complaint_confirm': 'Do you really want to delete this complaint?',
      'edit': 'Edit',
      'new_complaint': 'New complaint',
      'order_history': 'Order History',
      'no_orders': 'No orders found.',
      'order_label': 'Order',
      'pickup_time_label': 'Pickup time',
      'payment_label': 'Payment',
  'finalize_order': 'Finalize Order',
  'summary': 'Summary',
  'total': 'Total',
  'chosen_time': 'Chosen time',
  'payment_method': 'Payment method',
  'pay_on_spot': 'Pay on spot',
  'credit_card_sim': 'Credit card (simulation)',
  'confirm_order': 'Confirm Order',
  'no_reservations': 'No reservations found.',
  'reservation_history': 'Reservation History',
  'reservation_for': 'Reservation for',
  'reservation_on_at': 'On {date} at {time}',
  'reservation_deleted': 'Reservation deleted successfully.',
  'delete_reservation_confirm': 'Do you really want to delete this reservation?',
  'contact_info_title': 'Contact & Information',
  'phone_label': 'Phone',
  'whatsapp_label': 'WhatsApp',
  'location_label': 'Location',
  'facebook_label': 'Facebook',
  'opening_hours': 'Opening hours',
  'opening_hours_text': 'Mon - Sun: 11:30 - 14:30, 18:00 - 23:00',
  'visit_us': 'Come visit us in Sottomarina!',
    },
    'fr': {
      'no_account_found_for_email': 'Aucun compte trouvé pour cet email.',
      'password_reset_success': 'Mot de passe réinitialisé avec succès !',
      'verify_email': 'Vérifier l\'email',
      'email_found_enter_new_password': 'Email trouvé. Veuillez entrer votre nouveau mot de passe.',
      'new_password_label': 'Nouveau mot de passe',
      'reset_password': 'Réinitialiser le mot de passe',
      'password_too_short': 'Le mot de passe doit contenir au moins 6 caractères',
      'name_label': 'Nom complet',
      'confirm_password_label': 'Confirmer le mot de passe',
      'enter_name': 'Veuillez entrer votre nom',
      'enter_phone': 'Veuillez entrer votre numéro de téléphone',
      'enter_valid_email': 'Veuillez entrer un email valide',
      'email_already_used': 'Cet email est déjà utilisé.',
      'register_success': 'Inscription réussie! Vous pouvez vous connecter.',
      'register': 'Inscription',
      'register_with_google': 'S\'inscrire avec Google',
      'new_password_empty': 'Le nouveau mot de passe ne peut pas être vide',
      'passwords_do_not_match': 'Les mots de passe ne correspondent pas',
      'current_password_incorrect': 'Mot de passe actuel incorrect',
      'password_changed': 'Mot de passe mis à jour',
      'delete_account': 'Supprimer le compte',
      'delete_account_confirm': 'Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible.',
      'account_deleted': 'Compte supprimé',
      'email_label': 'Email',
      'password_label': 'Mot de passe',
      'forgot_password': 'Mot de passe oublié ?',
      'login': 'Se connecter',
      'login_with_google': 'Se connecter avec Google',
      'no_account_register': 'Pas de compte ? S\'inscrire',
      'banned_account': 'Ce compte a été banni.',
      'incorrect_credentials': 'Email ou mot de passe incorrect.',
      'google_cancelled': 'Connexion Google annulée',
      'enter_email': 'Veuillez entrer votre email',
      'enter_password': 'Veuillez entrer votre mot de passe',
      'app_title': 'Il Gabbiano',
      'our_menu': 'Notre Menu',
      'menu_empty': 'Le menu est vide pour le moment.',
      'added_to_cart': '{item} a été ajouté au panier!',
      'cart': 'Mon Panier',
      'place_order': 'Commander',
      'empty_cart': 'Votre panier est vide.',
      'confirm_delete': 'Confirmer la suppression',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'confirm': 'Confirmer',
      'gallery': 'Galerie',
      'camera': 'Caméra',
      'save': 'Sauvegarder',
      'pick_image_error': 'Erreur lors de la sélection de l\'image',
      'image_saved': 'Image enregistrée',
      'error': 'Erreur: {msg}',
      'no_feedbacks': 'Aucun avis pour le moment.',
      'feedback_deleted': 'Avis supprimé.',
      'reservation_sent': 'Réservation envoyée avec succès !',
      'reservation_updated': 'Réservation modifiée avec succès !',
      'order_success': 'Commande passée avec succès!',
      'photo_saved': 'Photo enregistrée',
      'profile_updated': 'Profil mis à jour avec succès !',
  'reservation_details': 'Détails de la réservation',
  'choose_date': 'Choisir une date',
  'choose_time': 'Choisir une heure',
  'select_date_time': 'Veuillez sélectionner la date et l\'heure',
  'number_of_people': 'Nombre de personnes',
  'required_field': 'Champ requis',
  'notes_optional': 'Remarques (optionnel)',
  'modify': 'Modifier',
  'reserve_action': 'Réserver',
      'menu': 'Commander à Emporter',
      'reserve': 'Réserver une Table',
      'my_orders': 'Mes Commandes',
  'my_reservations': 'Mes Réservations',
  'support': 'Support',
      'feedback': 'Donner un Avis',
      'complaints': 'Réclamations',
      'restaurant_info': 'Infos restaurant',
      'logout': 'Se déconnecter',
      'profile': 'Mon Profil',
      'language': 'Langue',
      'yes': 'Oui',
      'no': 'Non',
      'send': 'Envoyer',
      'update': 'Mettre à jour',
      'user_not_identified': 'Erreur: Utilisateur non identifié.',
      'select_rating': 'Veuillez sélectionner une note en étoiles.',
      'thank_you_feedback': 'Merci pour votre avis !',
      'delete_feedback': 'Supprimer l\'avis',
      'delete_feedback_confirm': 'Êtes-vous sûr de vouloir supprimer votre avis ?',
      'comment_optional': 'Commentaire (optionnel)',
      'comment_hint': 'Laissez-nous vos impressions...',
      'rating_prompt': 'Quelle note nous donneriez-vous ?',
      'complaint_history': 'Historique des réclamations',
      'no_complaints': 'Aucune réclamation trouvée.',
      'complaint_deleted': 'Réclamation supprimée avec succès.',
      'delete_complaint_confirm': 'Voulez-vous vraiment supprimer cette réclamation ?',
      'edit': 'Modifier',
      'new_complaint': 'Nouvelle réclamation',
      'order_history': 'Historique des Commandes',
      'no_orders': 'Aucune commande trouvée.',
      'order_label': 'Commande',
      'pickup_time_label': 'Heure de récupération',
      'payment_label': 'Paiement',
  'finalize_order': 'Finaliser la Commande',
  'summary': 'Récapitulatif',
  'total': 'Total',
  'chosen_time': 'Heure choisie',
  'payment_method': 'Méthode de paiement',
  'pay_on_spot': 'Paiement sur place',
  'credit_card_sim': 'Carte de crédit (simulation)',
  'confirm_order': 'Valider la commande',
  'no_reservations': 'Aucune réservation trouvée.',
  'reservation_history': 'Historique des réservations',
  'reservation_for': 'Réservation pour',
  'reservation_on_at': 'Le {date} à {time}',
  'reservation_deleted': 'Réservation supprimée avec succès.',
  'delete_reservation_confirm': 'Voulez-vous vraiment supprimer cette réservation ?',
  'contact_info_title': 'Contact & Informations',
  'phone_label': 'Téléphone',
  'whatsapp_label': 'WhatsApp',
  'location_label': 'Emplacement',
  'facebook_label': 'Facebook',
  'opening_hours': 'Horaires',
  'opening_hours_text': 'Lundi - Dimanche: 11:30 - 14:30, 18:00 - 23:00',
  'visit_us': 'Venez nous rendre visite à Sottomarina!',
    },
    'it': {
      'no_account_found_for_email': 'Nessun account trovato per questa email.',
      'password_reset_success': 'Password reimpostata con successo!',
      'verify_email': 'Verifica email',
      'email_found_enter_new_password': 'Email trovata. Inserisci la nuova password.',
      'new_password_label': 'Nuova password',
      'reset_password': 'Reimposta password',
      'password_too_short': 'La password deve contenere almeno 6 caratteri',
      'name_label': 'Nome completo',
      'confirm_password_label': 'Conferma password',
      'enter_name': 'Per favore inserisci il tuo nome',
      'enter_phone': 'Per favore inserisci il tuo numero di telefono',
      'enter_valid_email': 'Per favore inserisci un email valida',
      'email_already_used': 'Questa email è già utilizzata.',
      'register_success': 'Registrazione riuscita! Puoi ora accedere.',
      'register': 'Registrati',
      'register_with_google': 'Registrati con Google',
      'new_password_empty': 'La nuova password non può essere vuota',
      'passwords_do_not_match': 'Le password non corrispondono',
      'current_password_incorrect': 'Password corrente errata',
      'password_changed': 'Password aggiornata',
      'delete_account': 'Elimina account',
      'delete_account_confirm': 'Sei sicuro di voler eliminare il tuo account? Questa azione è irreversibile.',
      'account_deleted': 'Account eliminato',
      'email_label': 'Email',
      'password_label': 'Password',
      'forgot_password': 'Password dimenticata?',
      'login': 'Accedi',
      'login_with_google': 'Accedi con Google',
      'no_account_register': 'Nessun account? Registrati',
      'banned_account': 'Questo account è stato bannato.',
      'incorrect_credentials': 'Email o password errati.',
      'google_cancelled': 'Accesso Google annullato',
      'enter_email': 'Inserisci la tua email',
      'enter_password': 'Inserisci la tua password',
      'app_title': 'Il Gabbiano',
      'our_menu': 'Il nostro menu',
      'menu_empty': 'Il menu è vuoto per il momento.',
      'added_to_cart': '{item} aggiunto al carrello',
      'cart': 'Il mio carrello',
      'place_order': 'Ordina',
      'empty_cart': 'Il tuo carrello è vuoto.',
      'confirm_delete': 'Conferma eliminazione',
      'cancel': 'Annulla',
      'delete': 'Elimina',
      'confirm': 'Conferma',
      'gallery': 'Galleria',
      'camera': 'Fotocamera',
      'save': 'Salva',
      'pick_image_error': 'Errore nella selezione dell\'immagine',
      'image_saved': 'Immagine salvata',
      'error': 'Errore: {msg}',
      'no_feedbacks': 'Nessun feedback per il momento.',
      'feedback_deleted': 'Feedback eliminato.',
      'reservation_sent': 'Prenotazione inviata con successo!',
      'reservation_updated': 'Prenotazione modificata con successo!',
      'order_success': 'Ordine effettuato con successo!',
      'photo_saved': 'Foto salvata',
      'profile_updated': 'Profilo aggiornato con successo!',
  'reservation_details': 'Dettagli della prenotazione',
  'choose_date': 'Scegli una data',
  'choose_time': 'Scegli un orario',
  'select_date_time': 'Per favore seleziona data e ora',
  'number_of_people': 'Numero di persone',
  'required_field': 'Campo richiesto',
  'notes_optional': 'Note (opzionale)',
  'modify': 'Modifica',
  'reserve_action': 'Prenota',
      'menu': 'Ordina da asporto',
      'reserve': 'Prenota un tavolo',
      'my_orders': 'I miei ordini',
  'my_reservations': 'Le mie prenotazioni',
  'support': 'Supporto',
      'feedback': 'Lascia una recensione',
      'complaints': 'Reclami',
      'restaurant_info': 'Info ristorante',
      'logout': 'Disconnetti',
      'profile': 'Il mio profilo',
      'language': 'Lingua',
      'yes': 'Sì',
      'no': 'No',
      'send': 'Invia',
      'update': 'Aggiorna',
      'user_not_identified': 'Errore: utente non identificato.',
      'select_rating': 'Per favore seleziona una valutazione a stelle.',
      'thank_you_feedback': 'Grazie per il tuo feedback!',
      'delete_feedback': 'Elimina recensione',
      'delete_feedback_confirm': 'Sei sicuro di voler eliminare la tua recensione?',
      'comment_optional': 'Commento (opzionale)',
      'comment_hint': 'Lasciaci le tue impressioni...',
      'rating_prompt': 'Che voto ci daresti?',
      'complaint_history': 'Storico delle segnalazioni',
      'no_complaints': 'Nessuna segnalazione trovata.',
      'complaint_deleted': 'Segnalazione eliminata con successo.',
      'delete_complaint_confirm': 'Vuoi davvero eliminare questa segnalazione?',
      'edit': 'Modifica',
      'new_complaint': 'Nuova segnalazione',
      'order_history': 'Storico ordini',
      'no_orders': 'Nessun ordine trovato.',
      'order_label': 'Ordine',
      'pickup_time_label': 'Orario di ritiro',
      'payment_label': 'Pagamento',
  'finalize_order': 'Finalizza Ordine',
  'summary': 'Riepilogo',
  'total': 'Totale',
  'chosen_time': 'Orario scelto',
  'payment_method': 'Metodo di pagamento',
  'pay_on_spot': 'Paga sul posto',
  'credit_card_sim': 'Carta di credito (simulazione)',
  'confirm_order': 'Conferma ordine',
  'no_reservations': 'Nessuna prenotazione trovata.',
  'reservation_history': 'Storico prenotazioni',
  'reservation_for': 'Prenotazione per',
  'reservation_on_at': 'Il {date} alle {time}',
  'reservation_deleted': 'Prenotazione eliminata con successo.',
  'delete_reservation_confirm': 'Vuoi davvero eliminare questa prenotazione?',
  'contact_info_title': 'Contatto & Informazioni',
  'phone_label': 'Telefono',
  'whatsapp_label': 'WhatsApp',
  'location_label': 'Posizione',
  'facebook_label': 'Facebook',
  'opening_hours': 'Orari di apertura',
  'opening_hours_text': 'Lun - Dom: 11:30 - 14:30, 18:00 - 23:00',
  'visit_us': 'Vieni a trovarci a Sottomarina!',
    },
    'es': {
      'no_account_found_for_email': 'No se encontró cuenta para este correo.',
      'password_reset_success': '¡Contraseña restablecida con éxito!',
      'verify_email': 'Verificar email',
      'email_found_enter_new_password': 'Correo encontrado. Por favor ingrese su nueva contraseña.',
      'new_password_label': 'Nueva contraseña',
      'reset_password': 'Restablecer la contraseña',
      'password_too_short': 'La contraseña debe tener al menos 6 caracteres',
      'name_label': 'Nombre completo',
      'confirm_password_label': 'Confirmar contraseña',
      'enter_name': 'Por favor ingrese su nombre',
      'enter_phone': 'Por favor ingrese su número de teléfono',
      'enter_valid_email': 'Por favor ingrese un correo válido',
      'email_already_used': 'Este correo ya está en uso.',
      'register_success': 'Registro exitoso! Ahora puede iniciar sesión.',
      'register': 'Registrarse',
      'register_with_google': 'Registrarse con Google',
      'new_password_empty': 'La nueva contraseña no puede estar vacía',
      'passwords_do_not_match': 'Las contraseñas no coinciden',
      'current_password_incorrect': 'Contraseña actual incorrecta',
      'password_changed': 'Contraseña actualizada',
      'delete_account': 'Eliminar cuenta',
      'delete_account_confirm': '¿Está seguro de que desea eliminar su cuenta? Esta acción es irreversible.',
      'account_deleted': 'Cuenta eliminada',
      'email_label': 'Email',
      'password_label': 'Contraseña',
      'forgot_password': '¿Olvidaste la contraseña?',
      'login': 'Iniciar sesión',
      'login_with_google': 'Iniciar sesión con Google',
      'no_account_register': '¿No tienes cuenta? Registrarse',
      'banned_account': 'Esta cuenta ha sido baneada.',
      'incorrect_credentials': 'Email o contraseña incorrectos.',
      'google_cancelled': 'Inicio de sesión de Google cancelado',
      'enter_email': 'Por favor ingrese su correo',
      'enter_password': 'Por favor ingrese su contraseña',
      'app_title': 'Il Gabbiano',
      'our_menu': 'Nuestro Menú',
      'menu_empty': 'El menú está vacío por ahora.',
      'added_to_cart': '{item} ha sido añadido al carrito',
      'cart': 'Mi Carrito',
      'place_order': 'Realizar pedido',
      'empty_cart': 'Tu carrito está vacío.',
      'confirm_delete': 'Confirmar eliminación',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'confirm': 'Confirmar',
      'gallery': 'Galería',
      'camera': 'Cámara',
      'save': 'Guardar',
      'pick_image_error': 'Error al seleccionar la imagen',
      'image_saved': 'Imagen guardada',
      'error': 'Error: {msg}',
      'no_feedbacks': 'No hay opiniones por ahora.',
      'feedback_deleted': 'Opinión eliminada.',
      'reservation_sent': '¡Reserva enviada con éxito!',
      'reservation_updated': '¡Reserva modificada con éxito!',
      'order_success': '¡Pedido realizado con éxito!',
      'photo_saved': 'Foto guardada',
      'profile_updated': 'Perfil actualizado con éxito!',
  'reservation_details': 'Detalles de la reserva',
  'choose_date': 'Elegir una fecha',
  'choose_time': 'Elegir una hora',
  'select_date_time': 'Por favor seleccione fecha y hora',
  'number_of_people': 'Número de personas',
  'required_field': 'Campo requerido',
  'notes_optional': 'Notas (opcional)',
  'modify': 'Modificar',
  'reserve_action': 'Reservar',
      'menu': 'Pedir para llevar',
      'reserve': 'Reservar una mesa',
      'my_orders': 'Mis pedidos',
  'my_reservations': 'Mis Reservas',
  'support': 'Soporte',
      'feedback': 'Dar una opinión',
      'complaints': 'Reclamaciones',
      'restaurant_info': 'Información del restaurante',
      'logout': 'Cerrar sesión',
      'profile': 'Mi perfil',
      'language': 'Idioma',
      'yes': 'Sí',
      'no': 'No',
      'send': 'Enviar',
      'update': 'Actualizar',
      'user_not_identified': 'Error: usuario no identificado.',
      'select_rating': 'Por favor seleccione una calificación en estrellas.',
      'thank_you_feedback': '¡Gracias por tu opinión!',
      'delete_feedback': 'Eliminar opinión',
      'delete_feedback_confirm': '¿Está seguro de que desea eliminar su opinión?',
      'comment_optional': 'Comentario (opcional)',
      'comment_hint': 'Déjanos tus impresiones...',
      'rating_prompt': '¿Qué calificación nos darías?',
      'complaint_history': 'Historial de reclamaciones',
      'no_complaints': 'No se encontraron reclamaciones.',
      'complaint_deleted': 'Reclamación eliminada con éxito.',
      'delete_complaint_confirm': '¿Realmente desea eliminar esta reclamación?',
      'edit': 'Editar',
      'new_complaint': 'Nueva reclamación',
      'order_history': 'Historial de pedidos',
      'no_orders': 'No se encontraron pedidos.',
      'order_label': 'Pedido',
      'pickup_time_label': 'Hora de recogida',
      'payment_label': 'Pago',
  'finalize_order': 'Finalizar Pedido',
  'summary': 'Resumen',
  'total': 'Total',
  'chosen_time': 'Hora elegida',
  'payment_method': 'Método de pago',
  'pay_on_spot': 'Pagar en el lugar',
  'credit_card_sim': 'Tarjeta de crédito (simulación)',
  'confirm_order': 'Confirmar pedido',
  'no_reservations': 'No se encontraron reservas.',
  'reservation_history': 'Historial de Reservas',
  'reservation_for': 'Reserva para',
  'reservation_on_at': 'El {date} a las {time}',
  'reservation_deleted': 'Reserva eliminada con éxito.',
  'delete_reservation_confirm': '¿Realmente desea eliminar esta reserva?',
  'contact_info_title': 'Contacto & Información',
  'phone_label': 'Teléfono',
  'whatsapp_label': 'WhatsApp',
  'location_label': 'Ubicación',
  'facebook_label': 'Facebook',
  'opening_hours': 'Horario',
  'opening_hours_text': 'Lun - Dom: 11:30 - 14:30, 18:00 - 23:00',
  'visit_us': '¡Ven a visitarnos en Sottomarina!',
    },
    'de': {
      'no_account_found_for_email': 'Kein Konto für diese E-Mail gefunden.',
      'password_reset_success': 'Passwort erfolgreich zurückgesetzt!',
      'verify_email': 'E-Mail überprüfen',
      'email_found_enter_new_password': 'E-Mail gefunden. Bitte geben Sie Ihr neues Passwort ein.',
      'new_password_label': 'Neues Passwort',
      'reset_password': 'Passwort zurücksetzen',
      'password_too_short': 'Das Passwort muss mindestens 6 Zeichen lang sein',
      'name_label': 'Vollständiger Name',
      'confirm_password_label': 'Passwort bestätigen',
      'enter_name': 'Bitte geben Sie Ihren Namen ein',
      'enter_phone': 'Bitte geben Sie Ihre Telefonnummer ein',
      'enter_valid_email': 'Bitte geben Sie eine gültige E-Mail ein',
      'email_already_used': 'Diese E-Mail wird bereits verwendet.',
      'register_success': 'Registrierung erfolgreich! Sie können sich jetzt anmelden.',
      'register': 'Registrieren',
      'register_with_google': 'Mit Google registrieren',
      'new_password_empty': 'Neues Passwort darf nicht leer sein',
      'passwords_do_not_match': 'Passwörter stimmen nicht überein',
      'current_password_incorrect': 'Aktuelles Passwort falsch',
      'password_changed': 'Passwort aktualisiert',
      'delete_account': 'Konto löschen',
      'delete_account_confirm': 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Diese Aktion ist irreversibel.',
      'account_deleted': 'Konto gelöscht',
      'email_label': 'Email',
      'password_label': 'Passwort',
      'forgot_password': 'Passwort vergessen?',
      'login': 'Anmelden',
      'login_with_google': 'Mit Google anmelden',
      'no_account_register': 'Kein Konto? Registrieren',
      'banned_account': 'Dieses Konto wurde gesperrt.',
      'incorrect_credentials': 'Email oder Passwort falsch.',
      'google_cancelled': 'Google-Anmeldung abgebrochen',
      'enter_email': 'Bitte geben Sie Ihre E-Mail ein',
      'enter_password': 'Bitte geben Sie Ihr Passwort ein',
      'app_title': 'Il Gabbiano',
      'our_menu': 'Unser Menü',
      'menu_empty': 'Das Menü ist momentan leer.',
      'added_to_cart': '{item} wurde zum Warenkorb hinzugefügt',
      'cart': 'Mein Warenkorb',
      'place_order': 'Bestellen',
      'empty_cart': 'Ihr Warenkorb ist leer.',
      'confirm_delete': 'Löschen bestätigen',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'confirm': 'Bestätigen',
      'gallery': 'Galerie',
      'camera': 'Kamera',
      'save': 'Speichern',
      'pick_image_error': 'Fehler beim Auswählen des Bildes',
      'image_saved': 'Bild gespeichert',
      'error': 'Fehler: {msg}',
      'no_feedbacks': 'Noch keine Bewertungen.',
      'feedback_deleted': 'Bewertung gelöscht.',
      'reservation_sent': 'Reservierung erfolgreich gesendet!',
      'reservation_updated': 'Reservierung erfolgreich aktualisiert!',
      'order_success': 'Bestellung erfolgreich aufgegeben!',
      'photo_saved': 'Foto gespeichert',
      'profile_updated': 'Profil erfolgreich aktualisiert!',
  'reservation_details': 'Reservierungsdetails',
  'choose_date': 'Datum wählen',
  'choose_time': 'Uhrzeit wählen',
  'select_date_time': 'Bitte Datum und Uhrzeit auswählen',
  'number_of_people': 'Anzahl der Personen',
  'required_field': 'Pflichtfeld',
  'notes_optional': 'Notizen (optional)',
  'modify': 'Bearbeiten',
  'reserve_action': 'Reservieren',
      'menu': 'Bestellen',
      'reserve': 'Tisch reservieren',
      'my_orders': 'Meine Bestellungen',
  'my_reservations': 'Meine Reservierungen',
  'support': 'Support',
      'feedback': 'Feedback geben',
      'complaints': 'Beschwerden',
      'restaurant_info': 'Restaurant Info',
      'logout': 'Abmelden',
      'profile': 'Mein Profil',
      'language': 'Sprache',
      'yes': 'Ja',
      'no': 'Nein',
      'send': 'Senden',
      'update': 'Aktualisieren',
      'user_not_identified': 'Fehler: Benutzer nicht identifiziert.',
      'select_rating': 'Bitte wählen Sie eine Bewertung in Sternen.',
      'thank_you_feedback': 'Vielen Dank für Ihr Feedback!',
      'delete_feedback': 'Bewertung löschen',
      'delete_feedback_confirm': 'Möchten Sie Ihre Bewertung wirklich löschen?',
      'comment_optional': 'Kommentar (optional)',
      'comment_hint': 'Hinterlassen Sie uns Ihre Eindrücke...',
      'rating_prompt': 'Welche Bewertung würden Sie uns geben?',
      'complaint_history': 'Reklamationsverlauf',
      'no_complaints': 'Keine Reklamationen gefunden.',
      'complaint_deleted': 'Reklamation erfolgreich gelöscht.',
      'delete_complaint_confirm': 'Möchten Sie diese Reklamation wirklich löschen?',
      'edit': 'Bearbeiten',
      'new_complaint': 'Neue Reklamation',
      'order_history': 'Bestellverlauf',
      'no_orders': 'Keine Bestellungen gefunden.',
      'order_label': 'Bestellung',
      'pickup_time_label': 'Abholzeit',
      'payment_label': 'Zahlung',
  'finalize_order': 'Bestellung abschließen',
  'summary': 'Zusammenfassung',
  'total': 'Gesamt',
  'chosen_time': 'Ausgewählte Zeit',
  'payment_method': 'Zahlungsmethode',
  'pay_on_spot': 'Vor Ort zahlen',
  'credit_card_sim': 'Kreditkarte (Simulation)',
  'confirm_order': 'Bestellung bestätigen',
  'no_reservations': 'Keine Reservierungen gefunden.',
  'reservation_history': 'Reservierungsverlauf',
  'reservation_for': 'Reservierung für',
  'reservation_on_at': 'Am {date} um {time}',
  'reservation_deleted': 'Reservierung erfolgreich gelöscht.',
  'delete_reservation_confirm': 'Möchten Sie diese Reservierung wirklich löschen?',
  'contact_info_title': 'Kontakt & Informationen',
  'phone_label': 'Telefon',
  'whatsapp_label': 'WhatsApp',
  'location_label': 'Standort',
  'facebook_label': 'Facebook',
  'opening_hours': 'Öffnungszeiten',
  'opening_hours_text': 'Mo - So: 11:30 - 14:30, 18:00 - 23:00',
  'visit_us': 'Besuche uns in Sottomarina!',
    },
    'pt': {
      'no_account_found_for_email': 'Nenhuma conta encontrada para esse e-mail.',
      'password_reset_success': 'Senha redefinida com sucesso!',
      'verify_email': 'Verificar e-mail',
      'email_found_enter_new_password': 'E-mail encontrado. Por favor insira sua nova senha.',
      'new_password_label': 'Nova senha',
      'reset_password': 'Redefinir senha',
      'password_too_short': 'A senha deve ter pelo menos 6 caracteres',
      'name_label': 'Nome completo',
      'confirm_password_label': 'Confirmar senha',
      'enter_name': 'Por favor, insira seu nome',
      'enter_phone': 'Por favor, insira seu número de telefone',
      'enter_valid_email': 'Por favor, insira um email válido',
      'email_already_used': 'Este email já está em uso.',
      'register_success': 'Cadastro realizado com sucesso! Agora você pode fazer login.',
      'register': 'Registrar',
      'register_with_google': 'Registrar com Google',
      'new_password_empty': 'A nova senha não pode ficar vazia',
      'passwords_do_not_match': 'As senhas não coincidem',
      'current_password_incorrect': 'Senha atual incorreta',
      'password_changed': 'Senha atualizada',
      'delete_account': 'Excluir conta',
      'delete_account_confirm': 'Tem certeza de que deseja excluir sua conta? Esta ação é irreversível.',
      'account_deleted': 'Conta excluída',
      'email_label': 'Email',
      'password_label': 'Senha',
      'forgot_password': 'Esqueceu a senha?',
      'login': 'Entrar',
      'login_with_google': 'Entrar com Google',
      'no_account_register': 'Sem conta? Cadastre-se',
      'banned_account': 'Esta conta foi banida.',
      'incorrect_credentials': 'Email ou senha incorretos.',
      'google_cancelled': 'Login do Google cancelado',
      'enter_email': 'Por favor, insira seu email',
      'enter_password': 'Por favor, insira sua senha',
      'app_title': 'Il Gabbiano',
      'our_menu': 'Nosso Menu',
      'menu_empty': 'O menu está vazio por enquanto.',
      'added_to_cart': '{item} adicionado ao carrinho',
      'cart': 'Meu Carrinho',
      'place_order': 'Fazer pedido',
      'empty_cart': 'Seu carrinho está vazio.',
      'confirm_delete': 'Confirmar exclusão',
      'cancel': 'Cancelar',
      'delete': 'Excluir',
      'confirm': 'Confirmar',
      'gallery': 'Galeria',
      'camera': 'Câmera',
      'save': 'Salvar',
      'pick_image_error': 'Erro ao selecionar imagem',
      'image_saved': 'Imagem salva',
      'error': 'Erro: {msg}',
      'no_feedbacks': 'Nenhum comentário por enquanto.',
      'feedback_deleted': 'Comentário excluído.',
      'reservation_sent': 'Reserva enviada com sucesso!',
      'reservation_updated': 'Reserva modificada com sucesso!',
      'order_success': 'Pedido realizado com sucesso!',
      'photo_saved': 'Foto salva',
      'profile_updated': 'Perfil atualizado com sucesso!',
  'reservation_details': 'Detalhes da reserva',
  'choose_date': 'Escolher uma data',
  'choose_time': 'Escolher um horário',
  'select_date_time': 'Por favor selecione data e hora',
  'number_of_people': 'Número de pessoas',
  'required_field': 'Campo obrigatório',
  'notes_optional': 'Notas (opcional)',
  'modify': 'Modificar',
  'reserve_action': 'Reservar',
      'menu': 'Pedir',
      'reserve': 'Reservar uma mesa',
      'my_orders': 'Meus pedidos',
  'my_reservations': 'Minhas reservas',
  'support': 'Suporte',
      'feedback': 'Deixar um comentário',
      'complaints': 'Reclamações',
      'restaurant_info': 'Informações do restaurante',
      'logout': 'Sair',
      'profile': 'Meu perfil',
      'language': 'Idioma',
      'yes': 'Sim',
      'no': 'Não',
      'send': 'Enviar',
      'update': 'Atualizar',
      'user_not_identified': 'Erro: usuário não identificado.',
      'select_rating': 'Por favor, selecione uma classificação por estrelas.',
      'thank_you_feedback': 'Obrigado pelo seu feedback!',
      'delete_feedback': 'Excluir comentário',
      'delete_feedback_confirm': 'Tem certeza de que deseja excluir seu comentário?',
      'comment_optional': 'Comentário (opcional)',
      'comment_hint': 'Deixe-nos suas impressões...',
      'rating_prompt': 'Que nota você nos daria?',
      'complaint_history': 'Histórico de reclamações',
      'no_complaints': 'Nenhuma reclamação encontrada.',
      'complaint_deleted': 'Reclamação excluída com sucesso.',
      'delete_complaint_confirm': 'Deseja realmente excluir esta reclamação?',
      'edit': 'Editar',
      'new_complaint': 'Nova reclamação',
      'order_history': 'Histórico de pedidos',
      'no_orders': 'Nenhum pedido encontrado.',
      'order_label': 'Pedido',
      'pickup_time_label': 'Horário de retirada',
      'payment_label': 'Pagamento',
  'finalize_order': 'Finalizar Pedido',
  'summary': 'Resumo',
  'total': 'Total',
  'chosen_time': 'Hora escolhida',
  'payment_method': 'Método de pagamento',
  'pay_on_spot': 'Pagar no local',
  'credit_card_sim': 'Cartão de crédito (simulação)',
  'confirm_order': 'Confirmar pedido',
  'no_reservations': 'Nenhuma reserva encontrada.',
  'reservation_history': 'Histórico de Reservas',
  'reservation_for': 'Reserva para',
  'reservation_on_at': 'Em {date} às {time}',
  'reservation_deleted': 'Reserva excluída com sucesso.',
  'delete_reservation_confirm': 'Deseja realmente excluir esta reserva?',
  'contact_info_title': 'Contato & Informações',
  'phone_label': 'Telefone',
  'whatsapp_label': 'WhatsApp',
  'location_label': 'Localização',
  'facebook_label': 'Facebook',
  'opening_hours': 'Horário de funcionamento',
  'opening_hours_text': 'Seg - Dom: 11:30 - 14:30, 18:00 - 23:00',
  'visit_us': 'Venha nos visitar em Sottomarina!',
    },
    'ar': {
      'no_account_found_for_email': 'لم يتم العثور على حساب لهذا البريد الإلكتروني.',
      'password_reset_success': 'تم إعادة تعيين كلمة المرور بنجاح!',
      'verify_email': 'التحقق من البريد الإلكتروني',
      'email_found_enter_new_password': 'تم العثور على البريد الإلكتروني. الرجاء إدخال كلمة المرور الجديدة.',
      'new_password_label': 'كلمة المرور الجديدة',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'password_too_short': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'name_label': 'الاسم الكامل',
      'confirm_password_label': 'تأكيد كلمة المرور',
      'enter_name': 'الرجاء إدخال اسمك',
      'enter_phone': 'الرجاء إدخال رقم هاتفك',
      'enter_valid_email': 'الرجاء إدخال بريد إلكتروني صالح',
      'email_already_used': 'هذا البريد مستخدم بالفعل.',
      'register_success': 'تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.',
      'register': 'التسجيل',
      'register_with_google': 'التسجيل عبر جوجل',
      'new_password_empty': 'لا يمكن أن تكون كلمة المرور الجديدة فارغة',
      'passwords_do_not_match': 'كلمات المرور غير متطابقة',
      'current_password_incorrect': 'كلمة المرور الحالية غير صحيحة',
      'password_changed': 'تم تحديث كلمة المرور',
      'delete_account': 'حذف الحساب',
      'delete_account_confirm': 'هل أنت متأكد أنك تريد حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه.',
      'account_deleted': 'تم حذف الحساب',
      'email_label': 'البريد الإلكتروني',
      'password_label': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'login': 'تسجيل الدخول',
      'login_with_google': 'تسجيل الدخول عبر جوجل',
      'no_account_register': 'لا حساب؟ سجل',
      'banned_account': 'تم حظر هذا الحساب.',
      'incorrect_credentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      'google_cancelled': 'تم إلغاء تسجيل الدخول عبر جوجل',
      'enter_email': 'الرجاء إدخال البريد الإلكتروني',
      'enter_password': 'الرجاء إدخال كلمة المرور',
      'app_title': 'الْجَبَّيْنُ',
      'our_menu': 'قائمتنا',
      'menu_empty': 'القائمة فارغة الآن.',
      'added_to_cart': '{item} تمت إضافته إلى السلة',
      'cart': 'سلتي',
      'place_order': 'تقديم الطلب',
      'empty_cart': 'سلتك فارغة.',
      'confirm_delete': 'تأكيد الحذف',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'confirm': 'تأكيد',
      'gallery': 'المعرض',
      'camera': 'الكاميرا',
      'save': 'حفظ',
      'pick_image_error': 'خطأ في اختيار الصورة',
      'image_saved': 'تم حفظ الصورة',
      'error': 'خطأ: {msg}',
      'no_feedbacks': 'لا توجد آراء حتى الآن.',
      'feedback_deleted': 'تم حذف التقييم.',
      'reservation_sent': 'تم إرسال الحجز بنجاح!',
      'reservation_updated': 'تم تعديل الحجز بنجاح!',
      'order_success': 'تم تقديم الطلب بنجاح!',
      'photo_saved': 'تم حفظ الصورة',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح!',
  'reservation_details': 'تفاصيل الحجز',
  'choose_date': 'اختر تاريخًا',
  'choose_time': 'اختر وقتًا',
  'select_date_time': 'الرجاء تحديد التاريخ والوقت',
  'number_of_people': 'عدد الأشخاص',
  'required_field': 'حقل مطلوب',
  'notes_optional': 'ملاحظات (اختياري)',
  'modify': 'تعديل',
  'reserve_action': 'حجز',
      'menu': 'اطلب',
      'reserve': 'حجز طاولة',
      'my_orders': 'طلباتي',
  'my_reservations': 'حجوزاتي',
  'support': 'الدعم',
      'feedback': 'اراء',
      'complaints': 'الشكاوى',
      'restaurant_info': 'معلومات المطعم',
      'logout': 'تسجيل الخروج',
      'profile': 'ملفي',
      'language': 'اللغة',
      'yes': 'نعم',
      'no': 'لا',
      'send': 'إرسال',
      'update': 'تحديث',
      'user_not_identified': 'خطأ: المستخدم غير معروف.',
      'select_rating': 'يرجى تحديد تقييم بالنجوم.',
      'thank_you_feedback': 'شكرا لملاحظاتك!',
      'delete_feedback': 'حذف التقييم',
      'delete_feedback_confirm': 'هل أنت متأكد أنك تريد حذف تقييمك؟',
      'comment_optional': 'تعليق (اختياري)',
      'comment_hint': 'اترك انطباعاتك لنا...',
      'rating_prompt': 'ما التقييم الذي ستعطينا إياه؟',
      'complaint_history': 'سجل الشكاوى',
      'no_complaints': 'لم يتم العثور على شكاوى.',
      'complaint_deleted': 'تم حذف الشكوى بنجاح.',
      'delete_complaint_confirm': 'هل تريد حقًا حذف هذه الشكوى؟',
      'edit': 'تعديل',
      'new_complaint': 'شكوى جديدة',
      'order_history': 'سجل الطلبات',
      'no_orders': 'لم يتم العثور على طلبات.',
      'order_label': 'طلب',
      'pickup_time_label': 'وقت الاستلام',
      'payment_label': 'الدفع',
  'finalize_order': 'اكمال الطلب',
  'summary': 'ملخص',
  'total': 'المجموع',
  'chosen_time': 'الوقت المختار',
  'payment_method': 'طريقة الدفع',
  'pay_on_spot': 'الدفع في المكان',
  'credit_card_sim': 'بطاقة ائتمان (محاكاة)',
  'confirm_order': 'تأكيد الطلب',
  'no_reservations': 'لم يتم العثور على حجوزات.',
  'reservation_history': 'سجل الحجوزات',
  'reservation_for': 'حجز ل',
  'reservation_on_at': 'في {date} الساعة {time}',
  'reservation_deleted': 'تم حذف الحجز بنجاح.',
  'delete_reservation_confirm': 'هل تريد حقًا حذف هذا الحجز؟',
  'contact_info_title': 'الاتصال والمعلومات',
  'phone_label': 'الهاتف',
  'whatsapp_label': 'واتساب',
  'location_label': 'الموقع',
  'facebook_label': 'فيسبوك',
  'opening_hours': 'أوقات العمل',
  'opening_hours_text': 'الإثنين - الأحد: 11:30 - 14:30، 18:00 - 23:00',
  'visit_us': 'تعال زرنا في Sottomarina!',
    },
  };

  String t(String key) {
    final map = _localizedValues[locale.languageCode];
    final en = _localizedValues['en'];
    if (map != null && map.containsKey(key)) return map[key]!;
    if (en != null && en.containsKey(key)) return en[key]!;
    return key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'fr', 'it', 'es', 'de', 'pt', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
